FILE_NAME=hello.c
EXE_NAME=hello.exe


COMPILE=gcc ${FILE_NAME} -o ${EXE_NAME}
RUN=./${EXE_NAME}
CLEAR=rm ${EXE_NAME}

all:
	${COMPILE}
	${RUN}

compile:
	${COMPILE}


run:
	${RUN}


clear:
	${CLEAR}
